language: python

cache:
  - pip
  - ccache

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -U pip wheel
  - pip install cython
  - READTHEDOCS=True travis_wait pip install -U -e .[travis]

script:
  - flake8
  - flake8 --config=.flake8.cython
  - autopep8 -r . --diff | tee check_autopep8
  - test ! -s check_autopep8
  - python -Werror::DeprecationWarning -m compileall -f -q cupy cupyx examples tests docs
  - pushd docs
  - make html
  - popd

sudo: false
